/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation.Categorie;

import Dhelp.DAO.AddCommentDAO;
import Dhelp.DAO.CategorieDAO;
import Dhelp.entities.Admin;
import Dhelp.entities.Categorie;
import Dhelp.entities.Sujets;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ManageCategorie extends javax.swing.JFrame {
    Admin administrator = null;
    public ManageCategorie() {
        initComponents();
        bu_loadActionPerformed(null);
        jp_changename.setVisible(false);
        jp_addnewCat.setVisible(false);
    }
      public ManageCategorie(Admin a) {
        initComponents() ;
        administrator = a;
        
        bu_loadActionPerformed(null);
        jp_changename.setVisible(false);
        jp_addnewCat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        bu_deconnect = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bu_add = new javax.swing.JButton();
        bu_load = new javax.swing.JButton();
        jp_changename = new javax.swing.JPanel();
        tb_nomcat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bu_addnewCat = new javax.swing.JButton();
        tb_hide = new javax.swing.JButton();
        jp_addnewCat = new javax.swing.JPanel();
        tb_newnomCat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tb_add = new javax.swing.JButton();
        tb_hidenewCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/003.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tunga", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Gestion des categories");

        lb_login.setForeground(new java.awt.Color(0, 102, 204));
        lb_login.setText("jLabel3");

        bu_deconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/logout.png"))); // NOI18N
        bu_deconnect.setText("Deconnexion");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesMouseClicked(evt);
            }
        });
        tables.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tables);

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bu_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/miniadd.png"))); // NOI18N
        bu_add.setText("Ajouter");
        bu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bu_add)
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bu_add))
                .addGap(115, 115, 115))
        );

        bu_load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/Load.png"))); // NOI18N
        bu_load.setText("load");
        bu_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_loadActionPerformed(evt);
            }
        });

        jp_changename.setBorder(javax.swing.BorderFactory.createTitledBorder("Changer nom categorie"));

        jLabel3.setText("Nom categorie");

        bu_addnewCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/Upload (1).png"))); // NOI18N
        bu_addnewCat.setText("Save");
        bu_addnewCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_addnewCatActionPerformed(evt);
            }
        });

        tb_hide.setText("hide");
        tb_hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_changenameLayout = new javax.swing.GroupLayout(jp_changename);
        jp_changename.setLayout(jp_changenameLayout);
        jp_changenameLayout.setHorizontalGroup(
            jp_changenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_changenameLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jp_changenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_changenameLayout.createSequentialGroup()
                        .addComponent(tb_nomcat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jp_changenameLayout.createSequentialGroup()
                        .addComponent(bu_addnewCat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_hide)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp_changenameLayout.setVerticalGroup(
            jp_changenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_changenameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_changenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nomcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_changenameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bu_addnewCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_hide))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jp_addnewCat.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter Une nouvelle categorie"));

        jLabel4.setText("Nom categorie");

        tb_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/miniadd.png"))); // NOI18N
        tb_add.setText("Add");
        tb_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_addActionPerformed(evt);
            }
        });

        tb_hidenewCat.setText("hide");
        tb_hidenewCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hidenewCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_addnewCatLayout = new javax.swing.GroupLayout(jp_addnewCat);
        jp_addnewCat.setLayout(jp_addnewCatLayout);
        jp_addnewCatLayout.setHorizontalGroup(
            jp_addnewCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addnewCatLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_addnewCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addnewCatLayout.createSequentialGroup()
                        .addComponent(tb_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_hidenewCat))
                    .addComponent(tb_newnomCat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_addnewCatLayout.setVerticalGroup(
            jp_addnewCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addnewCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_addnewCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_newnomCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_addnewCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_add)
                    .addComponent(tb_hidenewCat))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bu_load)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bu_deconnect)
                            .addComponent(lb_login)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp_changename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_addnewCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_login)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bu_deconnect)
                                .addComponent(bu_load)))
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp_changename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_addnewCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bu_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_loadActionPerformed
        AddCommentDAO cat = new AddCommentDAO();
       ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for(Object em:(ArrayList)cat.GetNomCat())
                lp.add((Categorie)em);
        } catch (SQLException ex) {
           
        }

    DefaultTableModel amod = new DefaultTableModel();
    Object[] tableColumnNames = new Object[2];
    tableColumnNames[0]="id ";
    tableColumnNames[1]="Nom de la categorie "; 
    
       
    amod.setColumnIdentifiers(tableColumnNames);
    Object[] objects = new Object[2];
    if(lp.size()>0)
    {
        for(int i=0;i<lp.size();i++)
        {
            Categorie hashmap = lp.get(i);
            //objects[0]=hashmap.getNomSujet().toString();
            objects[0]=hashmap.getId_cat();
            objects[1]=hashmap.getNom_cat().toString();
            
            amod.addRow(objects);
        }
        this.tables.setModel(amod);
        
    }
    else{
        JOptionPane.showMessageDialog(null,"il nexiste pas encore des categorie ");
    }

    }//GEN-LAST:event_bu_loadActionPerformed

    private void tablesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablesKeyPressed
        //empty
    }//GEN-LAST:event_tablesKeyPressed

    private void tablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesMouseClicked
        CategorieDAO cat = new CategorieDAO();
        jp_changename.setVisible(true);
        try {
            //String nomSujet =(table_s.getModel().getValueAt(row, 0).toString());
            int row = tables.getSelectedRow();
            int idcat =((int)tables.getModel().getValueAt(row, 0));
            String nomcat=(tables.getModel().getValueAt(row, 1).toString());
            Categorie c = new Categorie(nomcat);
            tb_nomcat.setText(nomcat);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablesMouseClicked

    private void bu_addnewCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_addnewCatActionPerformed
       CategorieDAO cat = new CategorieDAO();
       if (tb_nomcat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "le champs  ne doit pas etre vide");
            
        }
        else if(tb_nomcat.getText().length()<5){
            JOptionPane.showMessageDialog(null, "veuileé saisir au moin 5 caractéres");
        }
        else {
            try {
               int row = tables.getSelectedRow();
            int idcat =((int)tables.getModel().getValueAt(row, 0));
            Categorie c = new Categorie(tb_nomcat.getText());
            cat.updateCategorie(c, idcat);
            JOptionPane.showMessageDialog(null, "la modification a ete enregistrer avec succes");
            bu_loadActionPerformed(null);
           } catch (Exception e) { JOptionPane.showMessageDialog(null,"erreur lors de linsertion "+e);
           }
            
        }
    }//GEN-LAST:event_bu_addnewCatActionPerformed

    private void bu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_addActionPerformed
        jp_addnewCat.setVisible(true);
       
    }//GEN-LAST:event_bu_addActionPerformed

    private void tb_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_addActionPerformed
        CategorieDAO cat = new CategorieDAO();
        
       if (tb_newnomCat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "le champs  ne doit pas etre vide");
            
        }
        else if(tb_newnomCat.getText().length()<5){
            JOptionPane.showMessageDialog(null, "veuileé saisir au moin 5 caractéres");
        }
        else {
            try {
                Categorie c = new Categorie(tb_newnomCat.getText());
                if(cat.findCategoriebyNom(tb_newnomCat.getText())){
                    JOptionPane.showMessageDialog(null, "le nom de cette categorie existe deja , veullié choisir un autre !");
                }
                else {
               cat.insertCategorie(c);
            JOptionPane.showMessageDialog(null, "Une nouvelle categorie vient detre creer");
            bu_loadActionPerformed(null);
                }
           } catch (Exception e) { JOptionPane.showMessageDialog(null,"erreur lors de linsertion "+e);
           }
            
        }
    }//GEN-LAST:event_tb_addActionPerformed

    private void tb_hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hideActionPerformed
       jp_changename.setVisible(false);
    }//GEN-LAST:event_tb_hideActionPerformed

    private void tb_hidenewCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hidenewCatActionPerformed
       jp_addnewCat.setVisible(false);
    }//GEN-LAST:event_tb_hidenewCatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lb_login.setText(administrator.getLogin_admin());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManageCategorie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_add;
    private javax.swing.JButton bu_addnewCat;
    private javax.swing.JButton bu_deconnect;
    private javax.swing.JButton bu_load;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_addnewCat;
    private javax.swing.JPanel jp_changename;
    private javax.swing.JLabel lb_login;
    private javax.swing.JTable tables;
    private javax.swing.JButton tb_add;
    private javax.swing.JButton tb_hide;
    private javax.swing.JButton tb_hidenewCat;
    private javax.swing.JTextField tb_newnomCat;
    private javax.swing.JTextField tb_nomcat;
    // End of variables declaration//GEN-END:variables
}
