/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation;

import Dhelp.presentation.Admin.*;
import Dhelp.DAO.*;
import Dhelp.DAO.CategorieDAO;
import Dhelp.entities.Article;
import Dhelp.entities.Categorie;
import Dhelp.entities.Personnes;
import Dhelp.presentation.Admin.Article_form;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.html.HTML;
import sun.util.calendar.BaseCalendar;
import sun.util.calendar.LocalGregorianCalendar;

/**
 *
 * @author marwen
 */
public class Ajout_article_form extends javax.swing.JFrame {
    Personnes personne = null;
    public Ajout_article_form() {
        initComponents();
        
                AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
    }
     public Ajout_article_form(Personnes p) {
        initComponents();
        personne = p;
        tb_login.setText(p.getLogin_personnes());
        
                AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_cat = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        quitter = new javax.swing.JButton();
        attach_file = new javax.swing.JButton();
        insert_article = new javax.swing.JButton();
        tf_attach = new javax.swing.JTextField();
        Nom_article = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description_article = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tb_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_catActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel1.setText("Ajouter article");

        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });

        attach_file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/Upload (1).png"))); // NOI18N
        attach_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_fileActionPerformed(evt);
            }
        });

        insert_article.setText("inserer");
        insert_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_articleActionPerformed(evt);
            }
        });

        tf_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_attachActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel2.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel3.setText("Description");

        jScrollPane1.setViewportView(Description_article);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/004.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel6.setText("Categorie");

        tb_login.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        tb_login.setForeground(new java.awt.Color(0, 153, 255));
        tb_login.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(quitter)
                        .addGap(22, 22, 22)
                        .addComponent(insert_article))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nom_article, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_attach, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attach_file, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tb_login))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tb_login))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nom_article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitter)
                            .addComponent(insert_article)))
                    .addComponent(attach_file, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dhelp.presentation.Admin.Article_form artform=new  Article_form();
        artform.setVisible(true);
        
    }//GEN-LAST:event_quitterActionPerformed

    private void attach_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_fileActionPerformed
        
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
       String filename=f.getAbsolutePath();
       Path path=Paths.get(filename);
       String ch=path.getParent().toString();
       String ch1=path.getFileName().toString();
       String ch2=ch.concat("/");
       String ch3=ch2.concat(ch1).replace('\\', '/');
        //ch3=ch.replace('\\', '/');
       tf_attach.setText(ch3);
        
        
    }//GEN-LAST:event_attach_fileActionPerformed

    private void insert_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_articleActionPerformed
      try{  
          
          String d = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
          Article article=new Article();
        String categ=cb_cat.getSelectedItem().toString();
        article.setNom_article(Nom_article.getText());
        article.setDescription_article(Description_article.getText());
        article.setDate_article(d);
        
        
        article.setChemin_fichier(tf_attach.getText());
        article.setCategorie(categ);
      
      JOptionPane.showMessageDialog(this,"Ajout faite avec succes");
      }
      catch(Exception ex){
          System.out.println(" erreur"+ex);
      }
    }//GEN-LAST:event_insert_articleActionPerformed

    private void tf_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_attachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_attachActionPerformed

    private void Date_article1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Date_article1MouseClicked
        
          
    }//GEN-LAST:event_Date_article1MouseClicked

    private void cb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_catActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_article_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_article_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_article_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_article_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_article_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Description_article;
    private javax.swing.JTextField Nom_article;
    private javax.swing.JButton attach_file;
    private javax.swing.JComboBox cb_cat;
    private javax.swing.JButton insert_article;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitter;
    private javax.swing.JLabel tb_login;
    private javax.swing.JTextField tf_attach;
    // End of variables declaration//GEN-END:variables
}
