/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation;

import Dhelp.DAO.AfficherDoctor;
import Dhelp.DAO.AuthentifiactionDAO;
import Dhelp.entities.Admin;
import Dhelp.entities.Personnes;
import Dhelp.presentation.*;
import Dhelp.presentation.Commentaire.AjouterCommentaire;
import Dhelp.presentation.Mail.RapportPourClient;
import Dhelp.presentation.Personnes.Ajouter_Client;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author user
 */
public class DrhelpMenu extends javax.swing.JFrame {
    Personnes pdr;
    Admin a =null;
    public DrhelpMenu(){
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    public DrhelpMenu(Admin admin) throws SQLException {
        initComponents();
        
        bu_Alertes.setEnabled(false);
        bu_article.setEnabled(false);
        bu_sujet.setEnabled(false);
        lb_login.setText(admin.getLogin_admin());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
 
    }
    public DrhelpMenu(Personnes p)
    {
        initComponents();
        bu_BoiteMedecin.setEnabled(false);
        tb_people.setEnabled(false);
        bu_categorie.setEnabled(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         pdr = p;
        lb_login.setText(p.getLogin_personnes());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bu_BoiteMedecin = new javax.swing.JButton();
        bu_Alertes = new javax.swing.JButton();
        bu_categorie = new javax.swing.JButton();
        bu_article = new javax.swing.JButton();
        bu_categorie2 = new javax.swing.JButton();
        tb_people = new javax.swing.JButton();
        bu_sujet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        lb_deconnect = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solution Administrative");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(240, 240, 240));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("PI Dev ESPRIT 2014 - All rights are reserved");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bu_BoiteMedecin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/001.png"))); // NOI18N
        bu_BoiteMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_BoiteMedecinActionPerformed(evt);
            }
        });

        bu_Alertes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/002.png"))); // NOI18N
        bu_Alertes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_AlertesActionPerformed(evt);
            }
        });

        bu_categorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/003.png"))); // NOI18N

        bu_article.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/004.png"))); // NOI18N

        bu_categorie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/005.png"))); // NOI18N

        tb_people.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/007.png"))); // NOI18N
        tb_people.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_peopleActionPerformed(evt);
            }
        });

        bu_sujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/0100.png"))); // NOI18N
        bu_sujet.setToolTipText("");
        bu_sujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_sujetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bu_BoiteMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bu_Alertes, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bu_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bu_article, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bu_categorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tb_people, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bu_sujet, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bu_article, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu_Alertes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu_BoiteMedecin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bu_categorie2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(tb_people, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu_sujet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel4.setText("Bienvenu : ");

        lb_login.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        lb_login.setForeground(new java.awt.Color(0, 153, 255));
        lb_login.setText("jLabel5");

        lb_deconnect.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        lb_deconnect.setForeground(new java.awt.Color(0, 102, 255));
        lb_deconnect.setText("Deconnexion");
        lb_deconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_deconnectMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/logoktiba.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_login)
                                .addGap(175, 175, 175)
                                .addComponent(lb_deconnect))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_login)
                    .addComponent(lb_deconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bu_BoiteMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_BoiteMedecinActionPerformed
        ShowDoctor sd = new ShowDoctor();
        this.setVisible(false);
        sd.setVisible(true);
    }//GEN-LAST:event_bu_BoiteMedecinActionPerformed

    private void tb_peopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_peopleActionPerformed
       Ajouter_Client ac = new Ajouter_Client();
       this.setVisible(false);
       ac.setVisible(true);
    }//GEN-LAST:event_tb_peopleActionPerformed

    private void bu_AlertesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_AlertesActionPerformed
        RapportPourClient rp = new RapportPourClient();
        this.setVisible(false);
        rp.setVisible(true);
    }//GEN-LAST:event_bu_AlertesActionPerformed

    private void bu_sujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_sujetActionPerformed
       AjouterCommentaire ac = new AjouterCommentaire(pdr);
       ac.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bu_sujetActionPerformed

    private void lb_deconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_deconnectMouseClicked
        this.setVisible(false);
        if(bu_BoiteMedecin.isEnabled()){
            LoginAdmin la = new LoginAdmin();
            la.setVisible(true);
        }
        else if(bu_sujet.isEnabled()){
            LoginDoctor ld = new LoginDoctor();
            ld.setVisible(true);
        }
            
    }//GEN-LAST:event_lb_deconnectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrhelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrhelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrhelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrhelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            
        
            public void run(){
               
                    new DrhelpMenu().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_Alertes;
    private javax.swing.JButton bu_BoiteMedecin;
    private javax.swing.JButton bu_article;
    private javax.swing.JButton bu_categorie;
    private javax.swing.JButton bu_categorie2;
    private javax.swing.JButton bu_sujet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_deconnect;
    private javax.swing.JLabel lb_login;
    private javax.swing.JButton tb_people;
    // End of variables declaration//GEN-END:variables
}
