/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation.Admin;

import Dhelp.DAO.AddCommentDAO;
import Dhelp.DAO.ArticleArticleDAO;
import Dhelp.entities.Admin;
import Dhelp.entities.Article;
import Dhelp.entities.Categorie;
import Dhelp.entities.Personnes;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class EvaluerArticleByAyoub extends javax.swing.JFrame {

    /**
     * Creates new form EvaluerArticleByAyoub
     */
    public EvaluerArticleByAyoub() {
        initComponents();
        AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
        tbloadActionPerformed(null);
        
    }
    public EvaluerArticleByAyoub(Personnes p) {
        initComponents();
        AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
        tbloadActionPerformed(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cb_cat = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesArticles = new javax.swing.JTable();
        tbload = new javax.swing.JButton();
        jp_const = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tf_chemainArticle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_noteArticle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nomArticle = new javax.swing.JTextField();
        tf_idArticle = new javax.swing.JTextField();
        evaluer_article = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_description = new javax.swing.JTextArea();
        tf_note = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel6.setText("Categorie");

        cb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_catActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tablesArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablesArticles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesArticlesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesArticles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        tbload.setText("load");
        tbload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbloadActionPerformed(evt);
            }
        });

        jp_const.setBackground(new java.awt.Color(153, 204, 255));
        jp_const.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setText("quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("lire l'article");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Evaluer");

        jLabel3.setText("Note");

        tf_noteArticle.setEnabled(false);

        jLabel2.setText("Description");

        jLabel5.setText("Nom de l'article");

        tf_idArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idArticleActionPerformed(evt);
            }
        });

        evaluer_article.setText("evaluer");
        evaluer_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluer_articleActionPerformed(evt);
            }
        });

        tf_description.setColumns(20);
        tf_description.setRows(5);
        jScrollPane2.setViewportView(tf_description);

        tf_note.setModel(new javax.swing.SpinnerNumberModel(10, 0, 20, 1));
        tf_note.setValue(10);

        javax.swing.GroupLayout jp_constLayout = new javax.swing.GroupLayout(jp_const);
        jp_const.setLayout(jp_constLayout);
        jp_constLayout.setHorizontalGroup(
            jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_constLayout.createSequentialGroup()
                .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(evaluer_article)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(69, 69, 69)
                        .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_constLayout.createSequentialGroup()
                                .addComponent(tf_nomArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_idArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addGap(0, 253, Short.MAX_VALUE)
                .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(tf_noteArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_chemainArticle)
                            .addComponent(tf_note, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                .addGap(168, 168, 168))
        );
        jp_constLayout.setVerticalGroup(
            jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_constLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nomArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noteArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_idArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_chemainArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_constLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jp_constLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(evaluer_article)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbload)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jp_const, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tbload))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_const, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_catActionPerformed

    private void tbloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbloadActionPerformed
           ArticleArticleDAO ad = new ArticleArticleDAO();
         
       ArrayList<Article> lp = new ArrayList<>();
       try{
       for(Object em:(ArrayList)ad.AfficherALLArticles())
           lp.add((Article)em);
       }catch(SQLException ex){}
       
    DefaultTableModel amod = new DefaultTableModel();
    Object[] tableColumnNames = new Object[8];
    tableColumnNames[0]="id";
    tableColumnNames[1]="nom Article ";
    tableColumnNames[2]="note article "; 
    tableColumnNames[3]="description article";
    tableColumnNames[4]="date article";
    tableColumnNames[5]="etat";
    tableColumnNames[6]="categorie";
    tableColumnNames[7]="chemin";
 
       
    amod.setColumnIdentifiers(tableColumnNames);
    Object[] objects = new Object[8];
    if(lp.size()>0)
    {
        for(int i=0;i<lp.size();i++)
        {
            Article hashmap = lp.get(i);
            objects[0]=hashmap.getId();
            objects[1]=hashmap.getNom_article().toString();
            objects[2]=hashmap.getNote_article();
            objects[3]=hashmap.getDescription_article().toString();
            objects[4]=hashmap.getDate_article().toString();
            objects[5]=hashmap.getEtat().toString();
            objects[6]=hashmap.getCategorie().toString();
            objects[7]=hashmap.getChemin_fichier().toString();
            
            
            amod.addRow(objects);
           
        }
        this.tablesArticles.setModel(amod);
        
    }   
    }//GEN-LAST:event_tbloadActionPerformed

    private void tablesArticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesArticlesMouseClicked
        
        try{
            int row = tablesArticles.getSelectedRow();
//           
            int id = ((int)tablesArticles.getModel().getValueAt(row, 0));
            String nomArticle = (tablesArticles.getModel().getValueAt(row, 1)).toString();
            float noteArticle = ((float)tablesArticles.getModel().getValueAt(row, 2));
            String descArticle = (tablesArticles.getModel().getValueAt(row, 3)).toString();
            String date = (tablesArticles.getModel().getValueAt(row, 4)).toString();
            String etat = (tablesArticles.getModel().getValueAt(row, 5)).toString();
            String categorie = (tablesArticles.getModel().getValueAt(row, 6)).toString();
            String chemin = (tablesArticles.getModel().getValueAt(row, 7)).toString();
            
            tf_chemainArticle.setText(chemin);
            tf_nomArticle.setText(nomArticle);
            tf_idArticle.setText(id+"");
            tf_description.setText(descArticle);
            tf_noteArticle.setText(noteArticle+"");
        
        
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tablesArticlesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            Article art = new Article();
            String chemin = art.getChemin_fichier();
            java.awt.Desktop.getDesktop().open(new File("" + tf_chemainArticle.getText() + ""));
            System.out.println(" " + chemin);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_idArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idArticleActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_tf_idArticleActionPerformed

    private void evaluer_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluer_articleActionPerformed
        int id = Integer.parseInt(tf_idArticle.getText());
        float ancienne_note = Float.parseFloat(tf_noteArticle.getText());
        float nouvelle_note = Float.parseFloat(tf_note.getValue().toString());
        ArticleArticleDAO articleDAO = new ArticleArticleDAO();
        Article art = new Article();
        float note = art.getNote_article();
        if (nouvelle_note > 20) {

            JOptionPane.showMessageDialog(this, "Veuillez entrez une note inférieur à 20");

        }
        try {
            articleDAO.EvaluerArticle(nouvelle_note, ancienne_note, id);
            JOptionPane.showMessageDialog(null, "l evaluation a ete effectuer avec succes ");
        } catch (SQLException ex) {
      
        }
       
        
    }//GEN-LAST:event_evaluer_articleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluerArticleByAyoub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluerArticleByAyoub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluerArticleByAyoub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluerArticleByAyoub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EvaluerArticleByAyoub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_cat;
    private javax.swing.JButton evaluer_article;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp_const;
    private javax.swing.JTable tablesArticles;
    private javax.swing.JButton tbload;
    private javax.swing.JTextField tf_chemainArticle;
    private javax.swing.JTextArea tf_description;
    private javax.swing.JTextField tf_idArticle;
    private javax.swing.JTextField tf_nomArticle;
    private javax.swing.JSpinner tf_note;
    private javax.swing.JTextField tf_noteArticle;
    // End of variables declaration//GEN-END:variables
}
