/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation.Admin;
import Dhelp.DAO.*;
import Dhelp.entities.*;
import Dhelp.presentation.AfficherListeCateg;
import Dhelp.presentation.MenuGestionCategorie;
import java.awt.Color;
import javax.swing.*;
import java.util.*;


/**
 *
 * @author marwen
 */
public class ListeCategoriese extends javax.swing.JFrame {

    /**
     * Creates new form ListeCategories
     */
    public ListeCategoriese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecateg = new javax.swing.JTable();
        Btnsupprimer = new javax.swing.JButton();
        ModifierCat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCat = new javax.swing.JTextField();
        btnretour = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablecateg.setModel(new AfficherListeCateg());
        tablecateg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecategMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecateg);

        Btnsupprimer.setText("Supprimer");
        Btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsupprimerActionPerformed(evt);
            }
        });

        ModifierCat.setText("Modifier");
        ModifierCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierCatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("Liste Catégories");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nom Catégorie");

        TxtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCatActionPerformed(evt);
            }
        });

        btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ModifierCat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TxtCat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(btnretour, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnretour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ModifierCat, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(Btnsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsupprimerActionPerformed
        
        
         int selected=tablecateg.getSelectedRow();
        System.out.println(""+selected);
   int table_clik=Integer.parseInt(tablecateg.getModel().getValueAt(selected, 0).toString());
        System.out.println(""+table_clik);
       
        
        
             JOptionPane.showConfirmDialog( null,  "voulez vous supprimer une catégorie?","suppression",
            JOptionPane.YES_NO_OPTION);
       
     CategorieDAO dao=new CategorieDAO();
        dao.deleteCategorieById(table_clik);
               
        tablecateg.setModel( new AfficherListeCateg());
        if(true){
            JOptionPane.showMessageDialog(null, "suppression avec succes");
        tablecateg.removeAll();
        }
         else {
            JOptionPane.showMessageDialog(null, "suppression non confirme");
        }
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_BtnsupprimerActionPerformed

    private void tablecategMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecategMouseClicked
        try { 
 
       int row =tablecateg.getSelectedRow();
       String txnom=(tablecateg.getModel().getValueAt(row, 0).toString());
       TxtCat.setText(txnom);
        
     
  }catch(Exception e){JOptionPane.showMessageDialog(null, e);
  }
    }//GEN-LAST:event_tablecategMouseClicked

    private void ModifierCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierCatActionPerformed
       
        CategorieDAO cat = new CategorieDAO();
        Categorie c = new Categorie();
        c.setNom_cat(TxtCat.getText());
        try{
        int row = tablecateg.getSelectedRow();
        int Table_click = Integer.parseInt((tablecateg.getModel().getValueAt(row, 1)).toString());
        cat.updateCategorie(c, Table_click);
        JOptionPane.showMessageDialog(null, "modification faite avec succes");
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_ModifierCatActionPerformed

    private void btnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretourActionPerformed
    
        
        MenuGestionCategorie menuGestionCategorie = new MenuGestionCategorie();
        this.setVisible(false);
        menuGestionCategorie.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnretourActionPerformed

    private void TxtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeCategoriese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeCategoriese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeCategoriese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeCategoriese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeCategoriese().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnsupprimer;
    private javax.swing.JButton ModifierCat;
    private javax.swing.JTextField TxtCat;
    private javax.swing.JButton btnretour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablecateg;
    // End of variables declaration//GEN-END:variables
}
