/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dhelp.presentation.Commentaire;
import Dhelp.DAO.AddCommentDAO;
import Dhelp.DAO.AddNewSubjectDAO;
import Dhelp.DAO.AfficherDoctor;
import Dhelp.entities.Categorie;
import Dhelp.entities.Commentaires;
import Dhelp.entities.Personnes;
import Dhelp.entities.Sujets;
import Dhelp.presentation.DrhelpMenu;
import Dhelp.presentation.LoginDoctor;
import Dhelp.presentation.Mail.ReclamationClient;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class AjouterCommentaire extends javax.swing.JFrame {
   Sujets loadsujet = null;
   Personnes ptdr=null ;
    private int dialogButton;
    public AjouterCommentaire() {
        
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        ta_contenu.setEditable(false);
        
                AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
        jp_tbsujet.setVisible(false);
        jp_sujet.setVisible(false);
        jp_comment.setVisible(false);
        

         
    }
     public AjouterCommentaire(Personnes p) {

         initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         ptdr=p;
         bu_update.setVisible(false);
        lb_login.setText(p.getLogin_personnes());
        ta_contenu.setEditable(false);
        
                AddCommentDAO ad = new AddCommentDAO();
        ArrayList<Categorie> lp = new ArrayList<>();
        try {
            for (Object em : (ArrayList) ad.GetNomCat()) {
                lp.add((Categorie) em);
            }
        } catch (SQLException ex) {}

        if (lp.size() > 0) {

            for (int i = 0; i < lp.size(); i++) {
                Categorie hashmap =lp.get(i);
                String nomc = hashmap.getNom_cat().toString();
                cb_cat.addItem(nomc);
                
            }
        }
        jp_tbsujet.setVisible(false);
        jp_sujet.setVisible(false);
        jp_comment.setVisible(false);
        

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cb_cat = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jp_tbsujet = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_s = new javax.swing.JTable();
        tb_hide = new javax.swing.JButton();
        bu_alert = new javax.swing.JButton();
        bu_update = new javax.swing.JButton();
        bu_delete = new javax.swing.JButton();
        tb_loadSujet = new javax.swing.JButton();
        jp_sujet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_nomSujet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_contenu = new javax.swing.JTextArea();
        tb_comment = new javax.swing.JButton();
        tb_hidesujet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lb_nbrcomm = new javax.swing.JLabel();
        jp_comment = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_commentaire = new javax.swing.JTextArea();
        tb_addCmt = new javax.swing.JButton();
        tb_cancel = new javax.swing.JButton();
        tb_hide3 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        tb_search = new javax.swing.JTextField();
        bu_search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lb_login = new javax.swing.JLabel();
        bu_deconnect = new javax.swing.JButton();
        tb_sujet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tunga", 0, 22)); // NOI18N
        jLabel2.setText("Forum et sujets");

        cb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_catActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/010.png"))); // NOI18N

        jp_tbsujet.setBackground(new java.awt.Color(204, 204, 255));
        jp_tbsujet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des sujets dans cette catégorie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tunga", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        table_s.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_sMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_s);

        tb_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/hide-left.png"))); // NOI18N
        tb_hide.setText("Hide");
        tb_hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hideActionPerformed(evt);
            }
        });

        bu_alert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/alert2.png"))); // NOI18N
        bu_alert.setText("Signaler ");
        bu_alert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_alertActionPerformed(evt);
            }
        });

        bu_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/system-software-update.png"))); // NOI18N
        bu_update.setText("Modifier");
        bu_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_updateActionPerformed(evt);
            }
        });

        bu_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/delete.png"))); // NOI18N
        bu_delete.setText("Supprimer");
        bu_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_tbsujetLayout = new javax.swing.GroupLayout(jp_tbsujet);
        jp_tbsujet.setLayout(jp_tbsujetLayout);
        jp_tbsujetLayout.setHorizontalGroup(
            jp_tbsujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tbsujetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_tbsujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_tbsujetLayout.createSequentialGroup()
                        .addComponent(tb_hide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_alert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bu_delete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jp_tbsujetLayout.setVerticalGroup(
            jp_tbsujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tbsujetLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_tbsujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_hide)
                    .addComponent(bu_alert)
                    .addComponent(bu_update)
                    .addComponent(bu_delete))
                .addContainerGap())
        );

        tb_loadSujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/search (2).png"))); // NOI18N
        tb_loadSujet.setText("Chercher");
        tb_loadSujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_loadSujetActionPerformed(evt);
            }
        });

        jp_sujet.setBackground(new java.awt.Color(255, 204, 51));
        jp_sujet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tunga", 0, 20))); // NOI18N

        jLabel3.setText("Sujet : ");

        lb_nomSujet.setText("jLabel4");

        ta_contenu.setColumns(20);
        ta_contenu.setLineWrap(true);
        ta_contenu.setRows(5);
        ta_contenu.setWrapStyleWord(true);
        ta_contenu.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ta_contenu.setEnabled(false);
        jScrollPane2.setViewportView(ta_contenu);

        tb_comment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/comment.png"))); // NOI18N
        tb_comment.setText("Commenter");
        tb_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_commentActionPerformed(evt);
            }
        });

        tb_hidesujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/hide-left.png"))); // NOI18N
        tb_hidesujet.setText("Hide");
        tb_hidesujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hidesujetActionPerformed(evt);
            }
        });

        jLabel4.setText("commentaires");

        lb_nbrcomm.setText("jLabel5");

        javax.swing.GroupLayout jp_sujetLayout = new javax.swing.GroupLayout(jp_sujet);
        jp_sujet.setLayout(jp_sujetLayout);
        jp_sujetLayout.setHorizontalGroup(
            jp_sujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sujetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_sujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jp_sujetLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_nomSujet)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_sujetLayout.createSequentialGroup()
                        .addComponent(tb_comment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_hidesujet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(lb_nbrcomm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jp_sujetLayout.setVerticalGroup(
            jp_sujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sujetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_sujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_nomSujet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jp_sujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tb_hidesujet)
                    .addComponent(jLabel4)
                    .addComponent(lb_nbrcomm))
                .addContainerGap())
        );

        jp_comment.setBackground(new java.awt.Color(204, 204, 255));
        jp_comment.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un commentaire"));

        ta_commentaire.setColumns(20);
        ta_commentaire.setRows(5);
        jScrollPane3.setViewportView(ta_commentaire);

        tb_addCmt.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\imagesDrhelp\\miniadd.png")); // NOI18N
        tb_addCmt.setText("Ajouter");
        tb_addCmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_addCmtActionPerformed(evt);
            }
        });

        tb_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/Cancel.png"))); // NOI18N
        tb_cancel.setText("Annuler");
        tb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cancelActionPerformed(evt);
            }
        });

        tb_hide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/hide-left.png"))); // NOI18N
        tb_hide3.setText("Hide");
        tb_hide3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hide3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_commentLayout = new javax.swing.GroupLayout(jp_comment);
        jp_comment.setLayout(jp_commentLayout);
        jp_commentLayout.setHorizontalGroup(
            jp_commentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_commentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_commentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_commentLayout.createSequentialGroup()
                        .addComponent(tb_addCmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_hide3)
                        .addGap(0, 250, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jp_commentLayout.setVerticalGroup(
            jp_commentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_commentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_commentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_addCmt)
                    .addComponent(tb_cancel)
                    .addComponent(tb_hide3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollBar1.setRequestFocusEnabled(true);
        jScrollBar1.setValueIsAdjusting(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tb_search.setBackground(new java.awt.Color(255, 204, 51));
        tb_search.setFont(new java.awt.Font("Tunga", 0, 12)); // NOI18N
        tb_search.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bu_search.setFont(new java.awt.Font("Tunga", 0, 14)); // NOI18N
        bu_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/search (2).png"))); // NOI18N
        bu_search.setText("search");
        bu_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_search, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bu_search)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bu_search, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/Back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lb_login.setForeground(new java.awt.Color(0, 153, 204));
        lb_login.setText("jLabel5");

        bu_deconnect.setText("Deconnexion");
        bu_deconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_deconnectActionPerformed(evt);
            }
        });

        tb_sujet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhelp/image/new (1).png"))); // NOI18N
        tb_sujet.setText("Sujet");
        tb_sujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_sujetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tb_loadSujet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tb_sujet)))
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jp_sujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jp_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lb_login)
                                        .addGap(18, 18, 18)
                                        .addComponent(bu_deconnect))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jp_tbsujet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tb_loadSujet)
                                            .addComponent(tb_sujet)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_login)
                                    .addComponent(bu_deconnect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jp_tbsujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp_comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_sujet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_catActionPerformed
        

    }//GEN-LAST:event_cb_catActionPerformed

    private void tb_loadSujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_loadSujetActionPerformed
        jp_tbsujet.setVisible(true);
        String nameCat = cb_cat.getSelectedItem().toString();
         AddCommentDAO ad = new AddCommentDAO();
       ArrayList<Sujets> lp = new ArrayList<>();
       try{
       for(Object em:(ArrayList)ad.AfficherSujet(nameCat))
           lp.add((Sujets)em);
       }catch(SQLException ex){}
       
    DefaultTableModel amod = new DefaultTableModel();
    Object[] tableColumnNames = new Object[6];
    tableColumnNames[0]="titre sujet ";
    tableColumnNames[1]="sujet "; 
    tableColumnNames[2]="date de creation";
    tableColumnNames[3]="id";
    tableColumnNames[4]="Auteur";
    tableColumnNames[5]="temps de creation";
   
       
    amod.setColumnIdentifiers(tableColumnNames);
    Object[] objects = new Object[6];
    if(lp.size()>0)
    {
        for(int i=0;i<lp.size();i++)
        {
            Sujets hashmap = lp.get(i);
            objects[0]=hashmap.getNomSujet().toString();
            objects[1]=hashmap.getContenuSujet().toString();
            objects[2]=hashmap.getDateCrSujet().toString();
            objects[3]=hashmap.getIdSujet();
            objects[4]=hashmap.getAuteurSujet().toString();
            objects[5]=hashmap.getTempsCrSujet().toString();
            
            amod.addRow(objects);
        }
        this.table_s.setModel(amod);
        
    }
    else{
        JOptionPane.showMessageDialog(null,"il nexiste pas encore des sujets dans cette categories");
    }

    }//GEN-LAST:event_tb_loadSujetActionPerformed

    private void tb_hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hideActionPerformed
      jp_tbsujet.setVisible(false);
    }//GEN-LAST:event_tb_hideActionPerformed

    private void bu_alertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_alertActionPerformed
        ReclamationClient rc = new ReclamationClient();
        rc.setVisible(true);
    }//GEN-LAST:event_bu_alertActionPerformed

    private void table_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_sMouseClicked
        jp_sujet.setVisible(true);
        AddCommentDAO ad = new AddCommentDAO();
        
                
        try{
            
            int row = table_s.getSelectedRow();
            String nomSujet =(table_s.getModel().getValueAt(row, 0).toString());
            String contenuSujet =(table_s.getModel().getValueAt(row, 1).toString());
            String DateCreSujet =(table_s.getModel().getValueAt(row, 2).toString());
            int idSujet = ((int)table_s.getModel().getValueAt(row, 3));
            String Auteursujet =(table_s.getModel().getValueAt(row, 4).toString());
            String tempCrSujet = (table_s.getModel().getValueAt(row, 5).toString());
            
            ta_contenu.setText(contenuSujet);
            lb_nomSujet.setText(nomSujet);
            //public Sujets(String nomSujet, String ContenuSujet, String dateCrSujet, int idSujet )
            
            Sujets s =  new Sujets(nomSujet, contenuSujet, DateCreSujet, idSujet, Auteursujet,tempCrSujet);
            int nc =ad.AfficherNbrCmnt(s.getIdSujet());
            loadsujet = s;
            lb_nbrcomm.setText(""+nc);
            if(ptdr.getLogin_personnes().equals(Auteursujet))
            {
                bu_update.setVisible(true);
                bu_delete.setVisible(true);
            }
            else
            {
                bu_update.setVisible(false);
                bu_delete.setVisible(false);
            }
        
        
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_sMouseClicked

    private void tb_hidesujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hidesujetActionPerformed
        jp_sujet.setVisible(false);
        
    }//GEN-LAST:event_tb_hidesujetActionPerformed

    private void tb_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_commentActionPerformed
      // AddCommentDAO ad = new AddCommentDAO();
        jp_comment.setVisible(true);
       
    }//GEN-LAST:event_tb_commentActionPerformed

    private void tb_addCmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_addCmtActionPerformed
       AddCommentDAO ad = new AddCommentDAO();
        if (ta_commentaire.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "le champs commentaire ne doit pas etre vide");
            
        }
        else if(ta_commentaire.getText().length()<10){
            JOptionPane.showMessageDialog(null, "veuileé saisir au moin 10 caractéres");
        }
        else {
        
        try{
            int row = table_s.getSelectedRow();
            int idsujet =((int)table_s.getModel().getValueAt(row, 3));
            String contenusujet = ta_commentaire.getText();
            String timeStamp = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
            String AuteurSuj = lb_login.getText();
            

          Commentaires cmt = new Commentaires(contenusujet, AuteurSuj, timeStamp,idsujet ); 
          ad.Addcommentaire(cmt);
          ad.IncrementerNbrCmt(idsujet);          
          JOptionPane.showMessageDialog(null, "votre commentaire a ete ajouter avec succes");
         
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
        }//public Commentaires(String contenuCmnt, String auteurCmnt, String dateCreationCmnt, int idSujetOriginal)
    }//GEN-LAST:event_tb_addCmtActionPerformed

    private void tb_hide3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hide3ActionPerformed
        jp_comment.setVisible(false);
    }//GEN-LAST:event_tb_hide3ActionPerformed

    private void tb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cancelActionPerformed
       ta_commentaire.setText("");
    }//GEN-LAST:event_tb_cancelActionPerformed

    private void tb_sujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_sujetActionPerformed
        AddNewSubject ad = new AddNewSubject(ptdr);
        ad.setVisible(true);
    }//GEN-LAST:event_tb_sujetActionPerformed

    private void bu_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_searchActionPerformed
        String stg = tb_search.getText().toString();
        jp_tbsujet.setVisible(true);
        AddNewSubjectDAO ad = new AddNewSubjectDAO();
       ArrayList<Sujets> lp = new ArrayList<>();
       try{
       for(Object em:(ArrayList)ad.SearchSujetByTopic(stg))
           lp.add((Sujets)em);
       }catch(SQLException ex){}
       
    DefaultTableModel amod = new DefaultTableModel();
    Object[] tableColumnNames = new Object[4];
    tableColumnNames[0]="titre sujet ";
    tableColumnNames[1]="sujet "; 
    tableColumnNames[2]="date de creation";
    tableColumnNames[3]="id";
   
       
    amod.setColumnIdentifiers(tableColumnNames);
    Object[] objects = new Object[4];
    if(lp.size()>0)
    {
        for(int i=0;i<lp.size();i++)
        {
            Sujets hashmap = lp.get(i);
            objects[0]=hashmap.getNomSujet().toString();
            objects[1]=hashmap.getContenuSujet().toString();
            objects[2]=hashmap.getDateCrSujet().toString();
            objects[3]=hashmap.getIdSujet();
            
            
            amod.addRow(objects);
        }
        this.table_s.setModel(amod);
        
    }
    else
    { JOptionPane.showMessageDialog(null, "pas de resultat trouve");
    }
    }//GEN-LAST:event_bu_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
        DrhelpMenu dr = null;
        
            dr = new DrhelpMenu(ptdr);
       
        dr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bu_deconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_deconnectActionPerformed
        this.setVisible(false);
        LoginDoctor dr = new LoginDoctor();
        dr.setVisible(true);
    }//GEN-LAST:event_bu_deconnectActionPerformed

    private void bu_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_updateActionPerformed
        AddNewSubject ad = new AddNewSubject(ptdr, loadsujet);
        this.setVisible(false);
        ad.setVisible(true);
    }//GEN-LAST:event_bu_updateActionPerformed

    private void bu_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_deleteActionPerformed
        AddCommentDAO ad = new AddCommentDAO();
        try {
            int dialogResult = JOptionPane.showConfirmDialog (null, "Voulez vous vraiment supprimer ce sujet ?","Warning",dialogButton);
if(dialogResult == JOptionPane.YES_OPTION){
            ad.DeleteSubject(loadsujet);}
            
        } catch (SQLException ex) {
            Logger.getLogger(AjouterCommentaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bu_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterCommentaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AjouterCommentaire().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_alert;
    private javax.swing.JButton bu_deconnect;
    private javax.swing.JButton bu_delete;
    private javax.swing.JButton bu_search;
    private javax.swing.JButton bu_update;
    private javax.swing.JComboBox cb_cat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jp_comment;
    private javax.swing.JPanel jp_sujet;
    private javax.swing.JPanel jp_tbsujet;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_nbrcomm;
    private javax.swing.JLabel lb_nomSujet;
    private javax.swing.JTextArea ta_commentaire;
    private javax.swing.JTextArea ta_contenu;
    private javax.swing.JTable table_s;
    private javax.swing.JButton tb_addCmt;
    private javax.swing.JButton tb_cancel;
    private javax.swing.JButton tb_comment;
    private javax.swing.JButton tb_hide;
    private javax.swing.JButton tb_hide3;
    private javax.swing.JButton tb_hidesujet;
    private javax.swing.JButton tb_loadSujet;
    private javax.swing.JTextField tb_search;
    private javax.swing.JButton tb_sujet;
    // End of variables declaration//GEN-END:variables
}
